//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfInterface.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://118.123.240.154:8080/hxBank/services/NetService", ConfigurationName="ServiceReference2.IntersServerImpl")]
    public interface IntersServerImpl {
        
        // CODEGEN: 消息 ProcessRequest 的包装命名空间(http://www.w3.org/2001/XMLSchema)以后生成的消息协定与默认值(https://118.123.240.154:8080/hxBank/services/NetService)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WcfInterface.ServiceReference2.ProcessResponse Process(WcfInterface.ServiceReference2.ProcessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Process", WrapperNamespace="http://www.w3.org/2001/XMLSchema", IsWrapped=true)]
    public partial class ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Request;
        
        public ProcessRequest() {
        }
        
        public ProcessRequest(string Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessResponse", WrapperNamespace="https://118.123.240.154:8080/hxBank/services/NetService", IsWrapped=true)]
    public partial class ProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ProcessReturn;
        
        public ProcessResponse() {
        }
        
        public ProcessResponse(string ProcessReturn) {
            this.ProcessReturn = ProcessReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntersServerImplChannel : WcfInterface.ServiceReference2.IntersServerImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntersServerImplClient : System.ServiceModel.ClientBase<WcfInterface.ServiceReference2.IntersServerImpl>, WcfInterface.ServiceReference2.IntersServerImpl {
        
        public IntersServerImplClient() {
        }
        
        public IntersServerImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntersServerImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntersServerImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntersServerImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfInterface.ServiceReference2.ProcessResponse WcfInterface.ServiceReference2.IntersServerImpl.Process(WcfInterface.ServiceReference2.ProcessRequest request) {
            return base.Channel.Process(request);
        }
        
        public string Process(string Request) {
            WcfInterface.ServiceReference2.ProcessRequest inValue = new WcfInterface.ServiceReference2.ProcessRequest();
            inValue.Request = Request;
            WcfInterface.ServiceReference2.ProcessResponse retVal = ((WcfInterface.ServiceReference2.IntersServerImpl)(this)).Process(inValue);
            return retVal.ProcessReturn;
        }
    }
}
