//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfInterface.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProPrice", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class ProPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double realpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weektimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double realprice {
            get {
                return this.realpriceField;
            }
            set {
                if ((this.realpriceField.Equals(value) != true)) {
                    this.realpriceField = value;
                    this.RaisePropertyChanged("realprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weektime {
            get {
                return this.weektimeField;
            }
            set {
                if ((object.ReferenceEquals(this.weektimeField, value) != true)) {
                    this.weektimeField = value;
                    this.RaisePropertyChanged("weektime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeSource", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class TradeSource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsConvertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int adjustcountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double coefficientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double coefxsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pricecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double waterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsConvert {
            get {
                return this.IsConvertField;
            }
            set {
                if ((this.IsConvertField.Equals(value) != true)) {
                    this.IsConvertField = value;
                    this.RaisePropertyChanged("IsConvert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int adjustcount {
            get {
                return this.adjustcountField;
            }
            set {
                if ((this.adjustcountField.Equals(value) != true)) {
                    this.adjustcountField = value;
                    this.RaisePropertyChanged("adjustcount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double coefficient {
            get {
                return this.coefficientField;
            }
            set {
                if ((this.coefficientField.Equals(value) != true)) {
                    this.coefficientField = value;
                    this.RaisePropertyChanged("coefficient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double coefxs {
            get {
                return this.coefxsField;
            }
            set {
                if ((this.coefxsField.Equals(value) != true)) {
                    this.coefxsField = value;
                    this.RaisePropertyChanged("coefxs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pricecode {
            get {
                return this.pricecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.pricecodeField, value) != true)) {
                    this.pricecodeField = value;
                    this.RaisePropertyChanged("pricecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rate {
            get {
                return this.rateField;
            }
            set {
                if ((this.rateField.Equals(value) != true)) {
                    this.rateField = value;
                    this.RaisePropertyChanged("rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double water {
            get {
                return this.waterField;
            }
            set {
                if ((this.waterField.Equals(value) != true)) {
                    this.waterField = value;
                    this.RaisePropertyChanged("water");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeRateInfo", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class TradeRateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WcfInterface.ServiceReference1.TradeRate> TradeRateInfoListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WcfInterface.ServiceReference1.TradeRate> TradeRateInfoList {
            get {
                return this.TradeRateInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeRateInfoListField, value) != true)) {
                    this.TradeRateInfoListField = value;
                    this.RaisePropertyChanged("TradeRateInfoList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeRate", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class TradeRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WaterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceCode {
            get {
                return this.PriceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceCodeField, value) != true)) {
                    this.PriceCodeField = value;
                    this.RaisePropertyChanged("PriceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Water {
            get {
                return this.WaterField;
            }
            set {
                if ((this.WaterField.Equals(value) != true)) {
                    this.WaterField = value;
                    this.RaisePropertyChanged("Water");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateSet", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class DateSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IstradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarttimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeekdayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endtime {
            get {
                return this.EndtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndtimeField, value) != true)) {
                    this.EndtimeField = value;
                    this.RaisePropertyChanged("Endtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Istrade {
            get {
                return this.IstradeField;
            }
            set {
                if ((this.IstradeField.Equals(value) != true)) {
                    this.IstradeField = value;
                    this.RaisePropertyChanged("Istrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceCode {
            get {
                return this.PriceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceCodeField, value) != true)) {
                    this.PriceCodeField = value;
                    this.RaisePropertyChanged("PriceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Starttime {
            get {
                return this.StarttimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StarttimeField, value) != true)) {
                    this.StarttimeField = value;
                    this.RaisePropertyChanged("Starttime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weekday {
            get {
                return this.WeekdayField;
            }
            set {
                if ((object.ReferenceEquals(this.WeekdayField, value) != true)) {
                    this.WeekdayField = value;
                    this.RaisePropertyChanged("Weekday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateSetInfoEx", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class DateSetInfoEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WcfInterface.ServiceReference1.DateSet> DtSetInfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WcfInterface.ServiceReference1.DateSet> DtSetInfoList {
            get {
                return this.DtSetInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.DtSetInfoListField, value) != true)) {
                    this.DtSetInfoListField = value;
                    this.RaisePropertyChanged("DtSetInfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateHolidayInfoEx", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class DateHolidayInfoEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WcfInterface.ServiceReference1.DateHoliday> DtHolidayInfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WcfInterface.ServiceReference1.DateHoliday> DtHolidayInfoList {
            get {
                return this.DtHolidayInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.DtHolidayInfoListField, value) != true)) {
                    this.DtHolidayInfoListField = value;
                    this.RaisePropertyChanged("DtHolidayInfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateHoliday", Namespace="http://schemas.datacontract.org/2004/07/JtMarketDistribution")]
    [System.SerializableAttribute()]
    public partial class DateHoliday : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoliNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StarttimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Endtime {
            get {
                return this.EndtimeField;
            }
            set {
                if ((this.EndtimeField.Equals(value) != true)) {
                    this.EndtimeField = value;
                    this.RaisePropertyChanged("Endtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoliName {
            get {
                return this.HoliNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HoliNameField, value) != true)) {
                    this.HoliNameField = value;
                    this.RaisePropertyChanged("HoliName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceCode {
            get {
                return this.PriceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceCodeField, value) != true)) {
                    this.PriceCodeField = value;
                    this.RaisePropertyChanged("PriceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Starttime {
            get {
                return this.StarttimeField;
            }
            set {
                if ((this.StarttimeField.Equals(value) != true)) {
                    this.StarttimeField = value;
                    this.RaisePropertyChanged("Starttime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ITrade.com/", ConfigurationName="ServiceReference1.ITrade")]
    public interface ITrade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetRealprice", ReplyAction="http://www.ITrade.com/ITrade/GetRealpriceResponse")]
        double GetRealprice(string strbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetRealData", ReplyAction="http://www.ITrade.com/ITrade/GetRealDataResponse")]
        string GetRealData(string strbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetProPrice", ReplyAction="http://www.ITrade.com/ITrade/GetProPriceResponse")]
        System.Collections.Generic.Dictionary<string, WcfInterface.ServiceReference1.ProPrice> GetProPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetAllLastPillar", ReplyAction="http://www.ITrade.com/ITrade/GetAllLastPillarResponse")]
        System.Collections.Generic.Dictionary<string, string> GetAllLastPillar(string weekflg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetLastPillarData", ReplyAction="http://www.ITrade.com/ITrade/GetLastPillarDataResponse")]
        string GetLastPillarData(string weekflg, string strbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetServerTime", ReplyAction="http://www.ITrade.com/ITrade/GetServerTimeResponse")]
        System.DateTime GetServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/SetRateAndWater", ReplyAction="http://www.ITrade.com/ITrade/SetRateAndWaterResponse")]
        int SetRateAndWater(string pricecode, double rate, double water);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/ModifyTradeDataSource", ReplyAction="http://www.ITrade.com/ITrade/ModifyTradeDataSourceResponse")]
        int ModifyTradeDataSource(WcfInterface.ServiceReference1.TradeSource tds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/AddTradeDataSource", ReplyAction="http://www.ITrade.com/ITrade/AddTradeDataSourceResponse")]
        int AddTradeDataSource(WcfInterface.ServiceReference1.TradeSource tds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetTradeRateInfo", ReplyAction="http://www.ITrade.com/ITrade/GetTradeRateInfoResponse")]
        WcfInterface.ServiceReference1.TradeRateInfo GetTradeRateInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/ModifyDateSet", ReplyAction="http://www.ITrade.com/ITrade/ModifyDateSetResponse")]
        bool ModifyDateSet(WcfInterface.ServiceReference1.DateSet DtSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetDateSetInfoEx", ReplyAction="http://www.ITrade.com/ITrade/GetDateSetInfoExResponse")]
        WcfInterface.ServiceReference1.DateSetInfoEx GetDateSetInfoEx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/GetHolidayInfoEx", ReplyAction="http://www.ITrade.com/ITrade/GetHolidayInfoExResponse")]
        WcfInterface.ServiceReference1.DateHolidayInfoEx GetHolidayInfoEx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/ModifyHoliday", ReplyAction="http://www.ITrade.com/ITrade/ModifyHolidayResponse")]
        bool ModifyHoliday(WcfInterface.ServiceReference1.DateHoliday Hliday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/AddHoliday", ReplyAction="http://www.ITrade.com/ITrade/AddHolidayResponse")]
        bool AddHoliday(WcfInterface.ServiceReference1.DateHoliday Hliday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ITrade.com/ITrade/DelHoliday", ReplyAction="http://www.ITrade.com/ITrade/DelHolidayResponse")]
        bool DelHoliday(string ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradeChannel : WcfInterface.ServiceReference1.ITrade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradeClient : System.ServiceModel.ClientBase<WcfInterface.ServiceReference1.ITrade>, WcfInterface.ServiceReference1.ITrade {
        
        public TradeClient() {
        }
        
        public TradeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetRealprice(string strbm) {
            return base.Channel.GetRealprice(strbm);
        }
        
        public string GetRealData(string strbm) {
            return base.Channel.GetRealData(strbm);
        }
        
        public System.Collections.Generic.Dictionary<string, WcfInterface.ServiceReference1.ProPrice> GetProPrice() {
            return base.Channel.GetProPrice();
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetAllLastPillar(string weekflg) {
            return base.Channel.GetAllLastPillar(weekflg);
        }
        
        public string GetLastPillarData(string weekflg, string strbm) {
            return base.Channel.GetLastPillarData(weekflg, strbm);
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        public int SetRateAndWater(string pricecode, double rate, double water) {
            return base.Channel.SetRateAndWater(pricecode, rate, water);
        }
        
        public int ModifyTradeDataSource(WcfInterface.ServiceReference1.TradeSource tds) {
            return base.Channel.ModifyTradeDataSource(tds);
        }
        
        public int AddTradeDataSource(WcfInterface.ServiceReference1.TradeSource tds) {
            return base.Channel.AddTradeDataSource(tds);
        }
        
        public WcfInterface.ServiceReference1.TradeRateInfo GetTradeRateInfo() {
            return base.Channel.GetTradeRateInfo();
        }
        
        public bool ModifyDateSet(WcfInterface.ServiceReference1.DateSet DtSet) {
            return base.Channel.ModifyDateSet(DtSet);
        }
        
        public WcfInterface.ServiceReference1.DateSetInfoEx GetDateSetInfoEx() {
            return base.Channel.GetDateSetInfoEx();
        }
        
        public WcfInterface.ServiceReference1.DateHolidayInfoEx GetHolidayInfoEx() {
            return base.Channel.GetHolidayInfoEx();
        }
        
        public bool ModifyHoliday(WcfInterface.ServiceReference1.DateHoliday Hliday) {
            return base.Channel.ModifyHoliday(Hliday);
        }
        
        public bool AddHoliday(WcfInterface.ServiceReference1.DateHoliday Hliday) {
            return base.Channel.AddHoliday(Hliday);
        }
        
        public bool DelHoliday(string ID) {
            return base.Channel.DelHoliday(ID);
        }
    }
}
